version: '3.8'

services:
  nginx:
    image: nginx:((PIAP_IMAGE_VERSION))
    container_name: nginx
    restart: unless-stopped
    ports:
      - "((PIAP_NGINX_PORT)):80"
    volumes:
      - nginx_data:/usr/share/nginx/html
      - nginx_config:/etc/nginx/conf.d

volumes:
  nginx_data:
  nginx_config:
